version: '3.2'

services:
  phoenix:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    environment:
      - ENV=dev
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
      - PGHOST=${PGHOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    #depends_on:
    #  - db
    command:
      - ./run.sh

  #db:
  #  image: postgres:9.6
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: postgres
  #    PGDATA: /var/lib/postgresql/data/pgdata
  #  restart: always
  #  volumes:
  #    - /var/lib/postgresql/data

#volumes:
#  pgdata:
